import { Coupon } from "@/types/coupon";
import CouponCarrefour from "@/assets/coupons/coupon-carrefour.png";
import CouponMilksha from "@/assets/coupons/coupon-milksha.png";
import CouponShowba from "@/assets/coupons/coupon-showba.png";
import CouponTrplus from "@/assets/coupons/coupon-trplus.png";

export const mockCoupons: Coupon[] = [
  {
    id: "1",
    image: CouponCarrefour,
    title: "家樂福 $100元現金抵用券",
    subtitle: "單筆消費滿$1,000即可使用",
    expiresIn: "2025-12-31",
    status: "available",
  },
  {
    id: "2",
    image: CouponMilksha,
    title: "迷客夏 蜂糖仙Ｑ晶凍系列",
    subtitle: "第二杯半價",
    expiresIn: "2025-10-15",
    status: "available",
  },
  {
    id: "3",
    image: CouponShowba,
    title: "秀泰影城 電影票根優惠",
    subtitle: "憑票根購買指定套餐享8折",
    expiresIn: "2025-09-01",
    status: "redeemed",
  },
  {
    id: "4",
    image: CouponTrplus,
    title: "特力屋 全館商品9折",
    subtitle: "部分商品除外，詳見店內公告",
    expiresIn: "2025-08-20",
    status: "expired",
  },
  {
    id: "5",
    image: CouponCarrefour,
    title: "家樂福 生鮮蔬果8折",
    subtitle: "限當日使用",
    expiresIn: "2025-11-30",
    status: "available",
  },
  {
    id: "6",
    image: CouponMilksha,
    title: "迷客夏 全品項買一送一",
    subtitle: "限同品項、冰熱、甜度",
    expiresIn: "2025-09-30",
    status: "available",
  },
  {
    id: "7",
    image: CouponShowba,
    title: "秀泰影城 爆米花組合",
    subtitle: "中杯爆米花+中杯飲料特價$99",
    expiresIn: "2025-12-31",
    status: "redeemed",
  },
  {
    id: "8",
    image: CouponTrplus,
    title: "特力屋 工具系列滿千送百",
    subtitle: "單筆消費滿$1,000送$100折價券",
    expiresIn: "2025-07-31",
    status: "expired",
  },
  {
    id: "9",
    image: CouponCarrefour,
    title: "家樂福 自有品牌9折",
    subtitle: "適用於所有家樂福自有品牌商品",
    expiresIn: "2026-01-31",
    status: "available",
  },
  {
    id: "10",
    image: CouponMilksha,
    title: "迷客夏 指定飲品折$10",
    subtitle: "適用於大正紅茶拿鐵、焙香決明大麥",
    expiresIn: "2025-11-15",
    status: "available",
  },
  {
    id: "11",
    image: CouponShowba,
    title: "秀泰影城 會員點數加倍",
    subtitle: "會員購票享點數2倍送",
    expiresIn: "2025-10-31",
    status: "redeemed",
  },
  {
    id: "12",
    image: CouponTrplus,
    title: "特力屋 燈具照明85折",
    subtitle: "特價品除外",
    expiresIn: "2025-09-15",
    status: "available",
  },
  {
    id: "13",
    image: CouponCarrefour,
    title: "家樂福 週末限定",
    subtitle: "消費滿$1,500享95折",
    expiresIn: "2025-12-28",
    status: "available",
  },
  {
    id: "14",
    image: CouponMilksha,
    title: "迷客夏 新品嚐鮮價",
    subtitle: "新品上市期間享9折優惠",
    expiresIn: "2025-08-31",
    status: "expired",
  },
  {
    id: "15",
    image: CouponShowba,
    title: "秀泰影城 IMAX電影票優惠",
    subtitle: "網路訂票享早鳥優惠價",
    expiresIn: "2026-02-28",
    status: "available",
  },
  {
    id: "16",
    image: CouponTrplus,
    title: "特力屋 廚具滿額贈",
    subtitle: "廚具系列消費滿$5,000贈好禮",
    expiresIn: "2025-11-20",
    status: "redeemed",
  },
  {
    id: "17",
    image: CouponCarrefour,
    title: "家樂福 線上購物免運",
    subtitle: "單筆消費滿$800即可享免運",
    expiresIn: "2025-10-10",
    status: "available",
  },
  {
    id: "18",
    image: CouponMilksha,
    title: "迷客夏 環保杯折扣",
    subtitle: "自備環保杯折$5",
    expiresIn: "2026-12-31",
    status: "available",
  },
  {
    id: "19",
    image: CouponShowba,
    title: "秀泰影城 生日我最大",
    subtitle: "當月壽星憑證件享電影票半價",
    expiresIn: "2025-12-31",
    status: "available",
  },
  {
    id: "20",
    image: CouponTrplus,
    title: "特力屋 DIY課程體驗券",
    subtitle: "報名指定DIY課程享9折",
    expiresIn: "2025-09-30",
    status: "redeemed",
  },
  {
    id: "21",
    image: CouponCarrefour,
    title: "家樂福 會員日滿額贈",
    subtitle: "每月8號會員日消費滿$2,000贈紅利點數",
    expiresIn: "2025-12-08",
    status: "available",
  },
  {
    id: "22",
    image: CouponMilksha,
    title: "迷客夏 學生專屬優惠",
    subtitle: "憑學生證享9折優惠",
    expiresIn: "2026-06-30",
    status: "available",
  },
  {
    id: "23",
    image: CouponShowba,
    title: "秀泰影城 信用卡合作優惠",
    subtitle: "指定信用卡購票享88折",
    expiresIn: "2025-12-31",
    status: "available",
  },
  {
    id: "24",
    image: CouponTrplus,
    title: "特力屋 居家收納系列",
    subtitle: "任選三件88折",
    expiresIn: "2025-10-31",
    status: "expired",
  },
];
